apiVersion: v1
kind: Namespace
metadata:
  name: kspan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kspan-event-viewer
  namespace: kspan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kspan-event-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregate-to-view
subjects:
- kind: ServiceAccount
  name: kspan-event-viewer
  namespace: kspan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kspan
  name: kspan
  namespace: kspan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kspan
  strategy: {}
  template:
    metadata:
      labels:
        app: kspan
    spec:
      serviceAccountName: kspan-event-viewer
      containers:
      - image: docker.io/weaveworks/kspan:v0.0
        name: kspan
        resources: {}
status: {}
