apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: kspan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: kspan-event-viewer
  namespace: kspan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: kspan-event-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregate-to-view
subjects:
- kind: ServiceAccount
  name: kspan-event-viewer
  namespace: kspan
